### ISSUE TITLE
Type error

### ISSUE THREAD

**Issue by taishi55** [ivanhofer/typesafe-i18n-demo-sveltekit#11]
My VS code shows the following type errors. 
I don't think it is important but it would be nice without the red lines. 

const localeTranslationLoaders: {}
const localeTranslations: {}

Element implicitly has an 'any' type because expression of type '"en"' can't be used to index type '{}'.
Property 'en' does not exist on type '{}'.ts(7053)

**Comment by ivanhofer** [comment]
From my point of view it looks like you don't have any [dictionaries](https://github.com/ivanhofer/typesafe-i18n/tree/main/packages/generator#locales) in your repository. The issues should be fixed when you add one and run the [`generator`](https://github.com/ivanhofer/typesafe-i18n/tree/main/packages/generator#generator) again.
