### ISSUE TITLE
update dependencies with example hooks.sever.ts

### ISSUE THREAD

**Issue by rootboard** [ivanhofer/typesafe-i18n-demo-sveltekit#12]
Hello,

After changes in 
[typesafe-i18n 5.13.1](https://github.com/ivanhofer/typesafe-i18n/blob/d957ce1f0615e060a242a600a0feef791ab6a89b/packages/detectors/src/detectors/server/accept-language-header.mts#L12)

I had to change [hooks.server.ts](https://github.com/ivanhofer/typesafe-i18n-demo-sveltekit/blob/b870ef0d701be9b9afecac80ad9fc37e4d4ce947/src/hooks.server.ts#L26)

```TS
const getPreferredLocale = (event: RequestEvent) => {
  // detect the preferred language the user has configured in his browser
  // https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Accept-Language
  const acceptLanguageDetector = initAcceptLanguageHeaderDetector({
    headers: event.request.headers
  });

  return detectLocale(acceptLanguageDetector);
};
```

It would be nice to update dependencies in repo and hooks.server.ts example file

**Comment by ivanhofer** [comment]
Thanks for letting me know. Fixed
