### ISSUE TITLE
Need help with svelte-kit

### ISSUE THREAD

**Issue by jodev7** [ivanhofer/typesafe-i18n-demo-sveltekit#13]
when i select the language everything works fine then when i reopen the page it changes to locale en how can i fix this

demo site: https://vegasgta5.vercel.app

code: https://github.com/Vegasrp-com/web-client/blob/master/src/hooks.server.ts

**Comment by ivanhofer** [comment]
Can you please describe the issue with some more details?

**Comment by jodev7** [comment]
yeah when i select russian lang locale changes to 'ru' but when i reopen browser or website locale changes to default 'en'

**Comment by ivanhofer** [comment]
If you are using SSR, then you would need to store the locale information in a cookie and not in local storage

**Comment by jodev7** [comment]
with cookie same bro when i reopen browser its changes to default 'en' locale
https://github.com/Vegasrp-com/web-client/blob/master/src/routes/%2Blayout.svelte

i think problem in +layout.ts file 
https://github.com/Vegasrp-com/web-client/blob/master/src/routes/%2Blayout.ts#L12

**Comment by ivanhofer** [comment]
You will need to write a custom logic here if no locale slug is present: https://github.com/Vegasrp-com/web-client/blob/master/src/hooks.server.ts#L15

YOu should set a cookie, once you switch locale and then read it in the `hooks.server.ts` file when you want to redirect the user. You can access SvelteKit's cookie implementation in any `*.server.ts` file: https://kit.svelte.dev/docs/load#cookies-and-headers

**Comment by jodev7** [comment]
thanks. i changes code in hooks.server.ts everything works

```ts
const getPreferredLocale = ({ cookies }: RequestEvent) => {
	const acceptLang = cookies.get('lang')
	
	if(acceptLang == undefined) {
		return 'en'
	} else {
		return acceptLang
	}
}
```

**Comment by ivanhofer** [comment]
perfect!
