### ISSUE TITLE
[help] autoredirect from domain/login to domain/en/login

### ISSUE THREAD

**Issue by rootboard** [ivanhofer/typesafe-i18n-demo-sveltekit#17]
Hello,

I'm looking for a solution for automatic redirect from the url where is no specified language (http://domain/login) to (http://domain/[lang]/login).
Are there any possibilities to make it?

**Comment by ivanhofer** [comment]
Hi, you will need to use rest parameters for the lang slug `[...lang]`: https://kit.svelte.dev/docs/advanced-routing#rest-parameters

When no lang slug is present, then you can redirect the user to the desired locale slug.

**Comment by mirostorm** [comment]
Hi,
I can't seem to find what I should put in the params in order for the rest parameter to work correcly.
When I change the name of the lang folder to `[...lang]`, the first part of the url just gets removed and I end up with a weird looking url (when not using a locale in the url).
e.g. --> (example.com/about) should become (example.com/en/about) but instead just becomes (example.com//)

**Comment by ivanhofer** [comment]
HI @raremiroir, If you change the url structure from this example, you will probably also need to change other parts of the code. Most things happen in `hooks.server.ts` and `LocaleSwitcher.svelte`. Take a look if something in those files causes the issues
