### ISSUE TITLE
[TypeError] some type errors are shown

### ISSUE THREAD

**Issue by taishi55** [ivanhofer/typesafe-i18n-demo-sveltekit#18]
1. `Cannot find module '$i18n/i18n-svelte' or its corresponding type declarations.ts(2307)` on `+layout.ts`
2. `Cannot find module '$i18n/i18n-util.async' or its corresponding type declarations.ts(2307)` on `+layout.ts`
3. `Property 'locale' does not exist on type 'Locals'.ts(2339)` on `+layout.server.ts`
4. `Object is possibly 'null'` at ```document.querySelector('html').setAttribute('lang', newLocale);``` on `LocaleSwitcher.svelte`

solution
1. `../i18n/i18n-svelt`
2. `../i18n/i18n-util.async`

**Comment by ivanhofer** [comment]
The example works fine for me. Did you run `npm run dev` first?

**Comment by taishi55** [comment]
Yes I initialized multiple times by `npm run dev` and Reload window on my VS code. Still I'm having the error. 

What I did was 

create a new app
```
npm create svelte@latest my-app
cd my-app
npm install
npm run dev -- --open
```

then install i18n
`npx typesafe-i18n --setup-auto`
`npm install typesafe-i18n `

**Comment by ivanhofer** [comment]
You need to define path aliases if you want to use the `$i18n` shorthand import: https://github.com/ivanhofer/typesafe-i18n-demo-sveltekit/blob/main/svelte.config.js

**Comment by taishi55** [comment]
I see. The part is not mentioned on the instruction. 

I still get errors for 3 and 4. 
3. `Property 'locale' does not exist on type 'Locals'.ts(2339)` on `+layout.server.ts`
4. `Object is possibly 'null' at document.querySelector('html').setAttribute('lang', newLocale);` on` LocaleSwitcher.svelte`

**Comment by ivanhofer** [comment]
Please check out the example repository. If it works there then you have something not configured correctly in your repo.

> I see. The part is not mentioned on the instruction.

This is an example repository using common techniques in the `vite` and `SvelteKit` world. I'm sorry but I can't explain every single line here.

**Comment by taishi55** [comment]
I've been trying to fix the type errors, and I still have no idea what I'm missing. Cloning your current repo gives me the same error once I open it. 

1. `Property 'log' does not exist on type 'TranslationFunctions'`
2. `Object is possibly 'null'.` at `document.querySelector('html').setAttribute('lang', newLocale)`

**Comment by taishi55** [comment]
To avoid `Object is possibly 'null'.` error, I modified the code below. 
```
// update `lang` attribute
const selectHtml = document?.querySelector('html');
if (selectHtml) {
	selectHtml.setAttribute('lang', newLocale);
}
```

I need your help for the error of `Property 'log' does not exist on type 'TranslationFunctions'`

**Comment by ivanhofer** [comment]
Did you clone this repo and without changing any line of code you get errors?

**Comment by taishi55** [comment]
@ivanhofer Sorry you are right. I was changing `vite.config.js` as below. 
```
import { sveltekit } from '@sveltejs/kit/vite';
import type { UserConfig } from 'vite';

const config: UserConfig = {
	plugins: [sveltekit()]
};

export default config;
```

I cannot wait to implement this library for my app! Thanks

**Comment by ivanhofer** [comment]
DId you find the issue? Does it work now?

**Comment by taishi55** [comment]
Yes the issue was using `import type { UserConfig } from 'vite';` instead of `import { defineConfig } from 'vite'`

**Comment by taishi55** [comment]
I think the instruction below (what I did) helps people who want to integrate this library on Sveltekit.

## 1. Create Sveltekit
```
npm create svelte@latest my-app
cd my-app
npm install
```
## 2. Install i18n libraries
`npx typesafe-i18n --setup-auto`
`npm i npm-run-all -D`
## 3. Copy & past the following codes to the specified file
**File Name:** `vite.config.js`
```
// @ts-check
import { defineConfig } from 'vite'
import { sveltekit } from '@sveltejs/kit/vite'

export default defineConfig({
	plugins: [sveltekit()],
	server: { port: 3000 },
	preview: { port: 3000 },
})
```

**File Name:** `tsconfig.json`
```
{
	"extends": "./.svelte-kit/tsconfig.json",
	"include": ["src/**/*.d.ts", "src/**/*.js", "src/**/*.ts", "src/**/*.svelte"],
	"compilerOptions": {
		"allowJs": true,
		"checkJs": true,
		"esModuleInterop": true,
		"forceConsistentCasingInFileNames": true,
		"resolveJsonModule": true,
		"skipLibCheck": true,
		"sourceMap": true,
		"strict": true
	}
	// Path aliases are handled by https://kit.svelte.dev/docs/configuration#alias
	//
	// If you want to overwrite includes/excludes, make sure to copy over the relevant includes/excludes
	// from the referenced tsconfig.json - TypeScript does not merge them in
}
```

**File Name:** `svelte.config.js`
```
import adapter from '@sveltejs/adapter-auto';
import preprocess from 'svelte-preprocess';

/** @type {import('@sveltejs/kit').Config} */
const config = {
	// Consult https://github.com/sveltejs/svelte-preprocess
	// for more information about preprocessors
	preprocess: preprocess(),

	kit: {
		adapter: adapter(),
		alias: {
			$i18n: 'src/i18n',
		},
	}
};

export default config;

```
## 4. Manually add the following code
Add below to a value of a `script` key in `packege.json`
```
"dev": "npm-run-all --parallel sveltekit typesafe-i18n",
"sveltekit": "vite dev",
```

## 5. Rename a file and then add the following code
**Rename**: `app.d.ts` to `global.d.ts`
```
/// <reference types="@sveltejs/kit" />

type Locales = import('$i18n/i18n-types').Locales
type TranslationFunctions = import('$i18n/i18n-types').TranslationFunctions

declare namespace App {
	interface Locals {
		locale: Locales
		LL: TranslationFunctions
	}

	// interface Platform { }
}
```

## 6. Create a file and paste the following code
**File Name**: `hooks.server.ts`
```
import { detectLocale, i18n, isLocale } from '$i18n/i18n-util'
import { loadAllLocales } from '$i18n/i18n-util.sync'
import type { Handle, RequestEvent } from '@sveltejs/kit'
import { initAcceptLanguageHeaderDetector } from 'typesafe-i18n/detectors'

loadAllLocales()
const L = i18n()

export const handle: Handle = async ({ event, resolve }) => {
	// read language slug
	const [, lang] = event.url.pathname.split('/')

	// redirect to base locale if no locale slug was found or if locale is not supported
	if (!lang || !isLocale(lang)) {
		const locale = getPreferredLocale(event)

		return new Response(null, {
			status: 302,
			headers: { 'Location': `/${locale}` }
		})
	}

	const locale = lang as Locales
	const LL = L[locale]

	// bind locale and translation functions to current request
	event.locals.locale = locale
	event.locals.LL = LL

	console.info(LL.log({ fileName: 'hooks.server.ts' }))

	// replace html lang attribute with correct language
	return resolve(event, { transformPageChunk: ({ html }) => html.replace('%lang%', lang) })
}

const getPreferredLocale = ({ request }: RequestEvent) => {
	// detect the preferred language the user has configured in his browser
	// https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Accept-Language
	const acceptLanguageDetector = initAcceptLanguageHeaderDetector(request)

	return detectLocale(acceptLanguageDetector)
}

```

## 7. Create a file and paste the following code
**File Name**: `utils.ts`
```
// replaces the locale slug in a relative url
// e.g. /en/blog/article-1 => /de/blog/article-1
export const replaceLocaleInUrl = (path: string, locale: string): string => {
	const [, , ...rest] = path.split('/')
	return `/${[locale, ...rest].join('/')}`
}
```

## 8. Delete the following file
`+page.svelte` (the default page) from `routes`

## 9. Copy & paste the following files
all files in `i18n`, `lib`, `routes` folders in [typesafe-i18n-demo-sveltekit](https://github.com/ivanhofer/typesafe-i18n-demo-sveltekit/tree/main/src)

## 10. Run the command below
`npm run dev`
