### ISSUE TITLE
Adding pages doesn't seem to work

### ISSUE THREAD

**Issue by Badlapje** [ivanhofer/typesafe-i18n-demo-sveltekit#2]
I've a project based on the example project.  I wanted to add a new page.  I tried fourthings, neither of which work:

1. add a tests/index.svelte file with some example content under routes (as per docs of sveltekit)
2. add a tests/index.svelte file under [lang], figuring that might be where i need to put everything.
3. add a test.svelte file under routes
4. add a test.svelte file under [lang]

Based on the docs, 1 or 3 should have definitely worked (not sure bout 2/4).  But maybe i'm missing something as i'm new to Svelte. 

I tried accessing with and without the lang param in all cases: localhost:3000/nl/test and localhost:3000/test.  All tries result in a redirect to the homepage.

**Comment by ivanhofer** [comment]
@Badlapje all your routes have to be located inside the `routes/[lang]/` folder.
e.g. when having a file `routes/[lang]/test.svelte` you can access it then by the slug `/en/test` or `/nl/test` in your browser.
So option 2 and 3 should actually work.
Do you have a `i18n/nl/index.ts` file in your project?
In the `load` function of the root `__layout.svelte` page, there is some redirect logic happening when using a locale that is not specified in your project:
https://github.com/ivanhofer/typesafe-i18n-demo-sveltekit/blob/da47bc897502bf7d7f86891492eb5ad851d392dd/src/routes/__layout.svelte#L14

**Comment by Badlapje** [comment]
I do, and i'm not sure what went wrong, but if i try it again then 2/4 do work.  Seems I messed something up and then unknowingly rectified it.

Thx for responding!

**Comment by ivanhofer** [comment]
Can you please share your repo? I'll try to find the issue why it's not working for you

**Comment by Badlapje** [comment]
I've found the issue  😄 

It seems that if there's an error in the component (doesn't matter which kind), the error status automatically redirects to the base locale page.  

So as an example, if i have an Option component like this:
```html
<section class="deliveryOptions">
    <h2 class="delivery__title">Waar mogen we het leveren?</h2>
    <ul class="delivery__options">
        {#each options as option (option.id)}
            <li>
                <DeliveryCard {option}/>
            </li>
        {/each}
    </ul>
</section>
```

and i call it wrongly like this (because i'm new at svelte or just forgot):
```html
<ul class="delivery__options">
    {#each options as option (option.id)}
        <li>
            <DeliveryCard option/><!-- not i should have used {option} -->
        </li>
    {/each}
</ul>
```

Then i very briefly get to see that error page before it redirects to the base locale index page.

I assume this bit in __layout.svelte is responsible:
```js
// redirect to preferred language if user comes from page root
if (!lang) {
  return {
    status: 302,
    redirect: `/${session.locale}`,
  }
}
```

but not well versed enough in svelte yet to have a quick solution respecting the error pages.  I still have to look up how to override those for my local project.

**Comment by ivanhofer** [comment]
@Badlapje thanks for investigating and sharing your findings.
I have updated this repo to add a workaround (and I also have fixed an issue in the `LocaleSwitcher` component). Please take a look at the latest two commits: https://github.com/ivanhofer/typesafe-i18n-demo-sveltekit/commit/62aea755a34941a6b60ef9e31909afdc2d592c0e https://github.com/ivanhofer/typesafe-i18n-demo-sveltekit/commit/8a489256a1e567e7a6911cc1f39e1aeffc5bd91b


I have opened an isssue in the SvelteKit repository: https://github.com/sveltejs/kit/issues/3647

**Comment by Badlapje** [comment]
@ivanhofer thx for creating a fix so quickly & opening the issue in Sveltekit.

Currently i'm getting this error when trying out the code, not sure why as i've upgraded to version 3 & it clearly should be a function.  Looking into it however.
```
TypeError: __vite_ssr_import_7__.setLocale is not a function
    at __layout.svelte:43:13
    at Object.$$render (/home/badlapje/gls/flex-delivery/services/frontend/node_modules/svelte/internal/index.js:1745:22)
    at root.svelte:37:45
    at $$render (/home/badlapje/gls/flex-delivery/services/frontend/node_modules/svelte/internal/index.js:1745:22)
    at Object.render (/home/badlapje/gls/flex-delivery/services/frontend/node_modules/svelte/internal/index.js:1753:26)
    at render_response (file:///home/badlapje/gls/flex-delivery/services/frontend/node_modules/@sveltejs/kit/dist/chunks/index.js:610:28)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async respond_with_error (file:///home/badlapje/gls/flex-delivery/services/frontend/node_modules/@sveltejs/kit/dist/chunks/index.js:1174:10)
    at async respond$1 (file:///home/badlapje/gls/flex-delivery/services/frontend/node_modules/@sveltejs/kit/dist/chunks/index.js:1425:4)
    at async render_page (file:///home/badlapje/gls/flex-delivery/services/frontend/node_modules/@sveltejs/kit/dist/chunks/index.js:1487:19)
```

**Comment by Badlapje** [comment]
And resolved it by relaunching the app after running a new build.  Cache problem 🤷 

The solution works like a charm 💯
