### ISSUE TITLE
Unintended navigation triggered by mutating $page.url

### ISSUE THREAD

**Issue by thenbe** [ivanhofer/typesafe-i18n-demo-sveltekit#25]
Is the url mutation in the util function on purpose? I don't have a complete understanding of how this library works but it seems at first glance that mutating the original `url.pathname` has unintended consequences/side effects. 

https://github.com/ivanhofer/typesafe-i18n-demo-sveltekit/blob/db87e65428764a5ee148e8da4795652b7a3c104e/src/utils.ts#L14

Related:
This sveltekit PR seems to indicate that mutating `$page.url` will trigger navigation. https://github.com/sveltejs/kit/pull/7827

**Comment by ivanhofer** [comment]
Hi @ambiguous48, this behaviour is custom to this specific implementation for this example. It has not really to do with the library itself.
I could not find any unintended side effects, but I decided to change the implementation. Thanks for the tip!

**Comment by thenbe** [comment]
Thank you for the quick reply. FWIW, it was causing the `$page.url.pathname` store to go out of sync in my app.
