### ISSUE TITLE
Default Locale not loading

### ISSUE THREAD

**Issue by ghost** [ivanhofer/typesafe-i18n-demo-sveltekit#27]
I have everything installed, and the work text translates just like I want, and it is amazing but when the website loads for some reason it does load the default lang causing no text to show at all until I select the lang. I don't know what the problem is. I will link my whole website repo as I am unsure what you need to help me. [REPO](https://github.com/Quadbit-Software/TidyMaids)

**Comment by ivanhofer** [comment]
Hi @Quadbit-Software, you need to load the locale first before selecting it. Here is an example: https://github.com/ivanhofer/typesafe-i18n-demo-sveltekit/blob/main/src/routes/%2Blayout.ts
