### ISSUE TITLE
Tailwind issue

### ISSUE THREAD

**Issue by marksteven** [ivanhofer/typesafe-i18n-demo-sveltekit#29]
Tried taking your boilerplate - installed working fine
Then added popular css module Tailwindcss
npx svelte-add@latest tailwindcss

which broke it
 with token error
<title>{&#x24;page.data.title || &apos;typesafe-i18n&apos;}</title>
                   ^
   20 |    <headhreflangs></headhreflangs>
Not quite sure why here
Now attempting to build SvelteKit/Tailwind boilerplate and then use your steps to add i18n
Will post here if I am successful
Hope this helps

**Comment by marksteven** [comment]
Further testing. Something I have not come across.
 It seems installing Tailwind runs a few scripts that rebuilt a number of pages that Tailwind deemed written wrong and broke.
+layout.svelte being the main one.
Breaking the i18n capability of switching languages. 
Fixing +layout.svelte got project to run properly so my suggestion to anyone else trying is keep a separate copy of +layout.svelte whilst you load Tailwind and repair if needed.

**Comment by ivanhofer** [comment]
Thanks for sharing this.
I'll close this issue, since it it not related to `typesafe-i18n`.
