### ISSUE TITLE
How to SSG a page or the website?

### ISSUE THREAD

**Issue by saostad** [ivanhofer/typesafe-i18n-demo-sveltekit#31]
I got this error while building the Sveltekit app in Vercel host:
```
Error: The following routes were marked as prerenderable, but were not prerendered because they were not found while crawling your app:
  - /[lang=lang],  - /[lang=lang]/biz/[id],  - /[lang=lang]/category/[slug],  - /[lang=lang]/contact,  - /[lang=lang]/register,  - /[lang=lang]/search
```

I understand for pages with parameters it can't guess, but for pages like / or /contact or /search why it can't?

Here is my param lang.ts file

```ts
import type { ParamMatcher } from '@sveltejs/kit';
import { isLocale } from '$i18n/i18n-util';

// only accept valid languages as a segment in the URL
export const match: ParamMatcher = (param) => {
	return isLocale(param);
};
```

**Comment by ivanhofer** [comment]
This is not an issue with `typesafe-i18n` itself. 
Please take a look at the `SvelteKit` dokumentation: https://kit.svelte.dev/docs/configuration#prerender
If you still have questions, please open an issue there. I too find the prerender documentation not that straightforward.

**Comment by saostad** [comment]
I fixed it by adding these lines in svelte.config.js:
```js
prerender: {
	entries: ['/en', '/fa']
}
```
and in my homepage +page.server.ts file
```ts
export const prerender = true;
```
