### ISSUE TITLE
on sveltekit 1.18.0 : lang attribute of html tag not updated

### ISSUE THREAD

**Issue by robthepaper** [ivanhofer/typesafe-i18n-demo-sveltekit#32]
Hi,
I just wanted to report that bug.

as title says, on 1.18.0 version of sveltekit
lang in:
<html lang="%lang%">

is update the first time but then doesn't update anymore when switching language.

I tried it on the latest release of typesafe-i18n-demo-sveltekit.

And this bug occurs starting with version 1.15.8 of @sveltejs/kit

**Comment by robthepaper** [comment]
Re,
for now I have a workaround by modifying LocalSwitcher.svelte like this : 
Basically always setting the attribute first.
```
const switchLocale = async (newLocale: Locales, updateHistoryState = true) => {
		console.log('LocalSwitcher.svelte', newLocale, updateHistoryState, $locale);

		// update `lang` attribute
		if (newLocale) document.querySelector('html').setAttribute('lang', newLocale);

		if (!newLocale || $locale === newLocale) return;
		console.log('===passed');

		// load new dictionary from server
		await loadLocaleAsync(newLocale);

		// select locale
		setLocale(newLocale);

		// update `lang` attribute
		//document.querySelector('html').setAttribute('lang', newLocale);

		if (updateHistoryState) {
			// update url to reflect locale changes
			history.pushState({ locale: newLocale }, '', replaceLocaleInUrl($page.url, newLocale));
		}

		// run the `load` function again
		invalidateAll();
	};

```

If anyone has a better solution and/or know why the new version of sveltekit does that.

**Comment by ivanhofer** [comment]
Thanks for the hint. I have updated the example: https://github.com/ivanhofer/typesafe-i18n-demo-sveltekit/commit/f9a0dbc121f2891d4096e5cb1177d89950e53cd3
