### ISSUE TITLE
Use `App.Session` type

### ISSUE THREAD

**Issue by svenjacobs** [ivanhofer/typesafe-i18n-demo-sveltekit#5]
This is just a minor improvement. Newer SvelteKit projects provide a `src/app.d.ts` type definitions file. Instead of defining your own `SessionPayload` type in `hooks.ts`, you could extend `App.Session` in `app.d.ts`. For eample:

```typescript
declare namespace App {
  interface Locals {}

  interface Platform {}

  interface Session {
    locale: Locales
  }

  interface Stuff {}
}
```

**Comment by ivanhofer** [comment]
Thanks @svenjacobs, I already saw that SvelteKit updated the docs this week, but I haven't had time to update the example yet. I will do it in the next couple of days.

**Comment by ivanhofer** [comment]
done!
